spring:
    application:
        name: backend
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        hibernate:
            naming:
                physical-strategy: ch.bus.rental.config.CustomPhysicalNamingStrategy
        show-sql: true
    sql:
        init:
            mode: always